sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker run inaetics/cagent_builder build_script > cagent_builder.sh && chmod +x cagent_builder.sh

install:
  - ./gradlew build
  - ./cagent_builder.sh make_bundles

deploy:
  provider: bintray
  file: $TRAVIS_BUILD_DIR/deployment.json
  user: $BINTRAY_USER
  key: $BINTRAY_KEY
