sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker run inaetics/cagent_builder build_script > cagent_builder.sh && chmod +x cagent_builder.sh

install:
  - ./gradlew jar
  - ./cagent_builder.sh make_bundles


after_success:
  - git config --global user.name "Travis CI"
  - git config --global user.email bpetri@gmx.net
  - git clone https://github.com/INAETICS/bundles.git $TRAVIS_BUILD_DIR/bundles && cd $TRAVIS_BUILD_DIR/bundles
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GITHUB_TOKEN:@github.com" > .git/credentials
  - cp $TRAVIS_BUILD_DIR/deploy/*.jar $TRAVIS_BUILD_DIR/org.inaetics.demonstrator.api/generated/*.jar $TRAVIS_BUILD_DIR/org.inaetics.demonstrator.java_impl/*.jar  $TRAVIS_BUILD_DIR/bundles/default-resources
  - git add default-resources/*.jar && git commit -m "build $TRAVIS_REPO_SLUG $TRAVIS_COMMIT" && git push -f
