//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: dds_builtinTopicsDcps.h
//  Source: dds_builtinTopicsDcps.idl
//  Generated: Tue Apr 15 00:36:29 2014
//  OpenSplice V6.4.140407OSS
//  
//******************************************************************
#ifndef _DDS_BUILTINTOPICSDCPS_H_
#define _DDS_BUILTINTOPICSDCPS_H_

#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"
#include "dds_dcps.h"
#include "dds_builtinTopics.h"


namespace DDS
{

   class ParticipantBuiltinTopicDataTypeSupportInterface;

   typedef ParticipantBuiltinTopicDataTypeSupportInterface * ParticipantBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < ParticipantBuiltinTopicDataTypeSupportInterface> ParticipantBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < ParticipantBuiltinTopicDataTypeSupportInterface> ParticipantBuiltinTopicDataTypeSupportInterface_out;


   class ParticipantBuiltinTopicDataDataWriter;

   typedef ParticipantBuiltinTopicDataDataWriter * ParticipantBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < ParticipantBuiltinTopicDataDataWriter> ParticipantBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < ParticipantBuiltinTopicDataDataWriter> ParticipantBuiltinTopicDataDataWriter_out;


   class ParticipantBuiltinTopicDataDataReader;

   typedef ParticipantBuiltinTopicDataDataReader * ParticipantBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < ParticipantBuiltinTopicDataDataReader> ParticipantBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < ParticipantBuiltinTopicDataDataReader> ParticipantBuiltinTopicDataDataReader_out;


   class ParticipantBuiltinTopicDataDataReaderView;

   typedef ParticipantBuiltinTopicDataDataReaderView * ParticipantBuiltinTopicDataDataReaderView_ptr;
   typedef DDS_DCPSInterface_var < ParticipantBuiltinTopicDataDataReaderView> ParticipantBuiltinTopicDataDataReaderView_var;
   typedef DDS_DCPSInterface_out < ParticipantBuiltinTopicDataDataReaderView> ParticipantBuiltinTopicDataDataReaderView_out;


   class TopicBuiltinTopicDataTypeSupportInterface;

   typedef TopicBuiltinTopicDataTypeSupportInterface * TopicBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < TopicBuiltinTopicDataTypeSupportInterface> TopicBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < TopicBuiltinTopicDataTypeSupportInterface> TopicBuiltinTopicDataTypeSupportInterface_out;


   class TopicBuiltinTopicDataDataWriter;

   typedef TopicBuiltinTopicDataDataWriter * TopicBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < TopicBuiltinTopicDataDataWriter> TopicBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < TopicBuiltinTopicDataDataWriter> TopicBuiltinTopicDataDataWriter_out;


   class TopicBuiltinTopicDataDataReader;

   typedef TopicBuiltinTopicDataDataReader * TopicBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < TopicBuiltinTopicDataDataReader> TopicBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < TopicBuiltinTopicDataDataReader> TopicBuiltinTopicDataDataReader_out;


   class TopicBuiltinTopicDataDataReaderView;

   typedef TopicBuiltinTopicDataDataReaderView * TopicBuiltinTopicDataDataReaderView_ptr;
   typedef DDS_DCPSInterface_var < TopicBuiltinTopicDataDataReaderView> TopicBuiltinTopicDataDataReaderView_var;
   typedef DDS_DCPSInterface_out < TopicBuiltinTopicDataDataReaderView> TopicBuiltinTopicDataDataReaderView_out;


   class PublicationBuiltinTopicDataTypeSupportInterface;

   typedef PublicationBuiltinTopicDataTypeSupportInterface * PublicationBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < PublicationBuiltinTopicDataTypeSupportInterface> PublicationBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < PublicationBuiltinTopicDataTypeSupportInterface> PublicationBuiltinTopicDataTypeSupportInterface_out;


   class PublicationBuiltinTopicDataDataWriter;

   typedef PublicationBuiltinTopicDataDataWriter * PublicationBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < PublicationBuiltinTopicDataDataWriter> PublicationBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < PublicationBuiltinTopicDataDataWriter> PublicationBuiltinTopicDataDataWriter_out;


   class PublicationBuiltinTopicDataDataReader;

   typedef PublicationBuiltinTopicDataDataReader * PublicationBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < PublicationBuiltinTopicDataDataReader> PublicationBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < PublicationBuiltinTopicDataDataReader> PublicationBuiltinTopicDataDataReader_out;


   class PublicationBuiltinTopicDataDataReaderView;

   typedef PublicationBuiltinTopicDataDataReaderView * PublicationBuiltinTopicDataDataReaderView_ptr;
   typedef DDS_DCPSInterface_var < PublicationBuiltinTopicDataDataReaderView> PublicationBuiltinTopicDataDataReaderView_var;
   typedef DDS_DCPSInterface_out < PublicationBuiltinTopicDataDataReaderView> PublicationBuiltinTopicDataDataReaderView_out;


   class SubscriptionBuiltinTopicDataTypeSupportInterface;

   typedef SubscriptionBuiltinTopicDataTypeSupportInterface * SubscriptionBuiltinTopicDataTypeSupportInterface_ptr;
   typedef DDS_DCPSInterface_var < SubscriptionBuiltinTopicDataTypeSupportInterface> SubscriptionBuiltinTopicDataTypeSupportInterface_var;
   typedef DDS_DCPSInterface_out < SubscriptionBuiltinTopicDataTypeSupportInterface> SubscriptionBuiltinTopicDataTypeSupportInterface_out;


   class SubscriptionBuiltinTopicDataDataWriter;

   typedef SubscriptionBuiltinTopicDataDataWriter * SubscriptionBuiltinTopicDataDataWriter_ptr;
   typedef DDS_DCPSInterface_var < SubscriptionBuiltinTopicDataDataWriter> SubscriptionBuiltinTopicDataDataWriter_var;
   typedef DDS_DCPSInterface_out < SubscriptionBuiltinTopicDataDataWriter> SubscriptionBuiltinTopicDataDataWriter_out;


   class SubscriptionBuiltinTopicDataDataReader;

   typedef SubscriptionBuiltinTopicDataDataReader * SubscriptionBuiltinTopicDataDataReader_ptr;
   typedef DDS_DCPSInterface_var < SubscriptionBuiltinTopicDataDataReader> SubscriptionBuiltinTopicDataDataReader_var;
   typedef DDS_DCPSInterface_out < SubscriptionBuiltinTopicDataDataReader> SubscriptionBuiltinTopicDataDataReader_out;


   class SubscriptionBuiltinTopicDataDataReaderView;

   typedef SubscriptionBuiltinTopicDataDataReaderView * SubscriptionBuiltinTopicDataDataReaderView_ptr;
   typedef DDS_DCPSInterface_var < SubscriptionBuiltinTopicDataDataReaderView> SubscriptionBuiltinTopicDataDataReaderView_var;
   typedef DDS_DCPSInterface_out < SubscriptionBuiltinTopicDataDataReaderView> SubscriptionBuiltinTopicDataDataReaderView_out;

   struct ParticipantBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < ParticipantBuiltinTopicData, struct ParticipantBuiltinTopicDataSeq_uniq_> ParticipantBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < ParticipantBuiltinTopicDataSeq> ParticipantBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < ParticipantBuiltinTopicDataSeq> ParticipantBuiltinTopicDataSeq_out;
   class ParticipantBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef ParticipantBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef ParticipantBuiltinTopicDataTypeSupportInterface_var _var_type;

      static ParticipantBuiltinTopicDataTypeSupportInterface_ptr _duplicate (ParticipantBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static ParticipantBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      ParticipantBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      ParticipantBuiltinTopicDataTypeSupportInterface () {};
      ~ParticipantBuiltinTopicDataTypeSupportInterface () {};
   private:
      ParticipantBuiltinTopicDataTypeSupportInterface (const ParticipantBuiltinTopicDataTypeSupportInterface &);
      ParticipantBuiltinTopicDataTypeSupportInterface & operator = (const ParticipantBuiltinTopicDataTypeSupportInterface &);
   };

   class ParticipantBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef ParticipantBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef ParticipantBuiltinTopicDataDataWriter_var _var_type;

      static ParticipantBuiltinTopicDataDataWriter_ptr _duplicate (ParticipantBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static ParticipantBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      ParticipantBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual LongLong register_instance (const ParticipantBuiltinTopicData& instance_data) = 0;
      virtual LongLong register_instance_w_timestamp (const ParticipantBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const ParticipantBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const ParticipantBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const ParticipantBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long write_w_timestamp (const ParticipantBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const ParticipantBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long dispose_w_timestamp (const ParticipantBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const ParticipantBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const ParticipantBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (ParticipantBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const ParticipantBuiltinTopicData& instance_data) = 0;

   protected:
      ParticipantBuiltinTopicDataDataWriter () {};
      ~ParticipantBuiltinTopicDataDataWriter () {};
   private:
      ParticipantBuiltinTopicDataDataWriter (const ParticipantBuiltinTopicDataDataWriter &);
      ParticipantBuiltinTopicDataDataWriter & operator = (const ParticipantBuiltinTopicDataDataWriter &);
   };

   class ParticipantBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef ParticipantBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef ParticipantBuiltinTopicDataDataReader_var _var_type;

      static ParticipantBuiltinTopicDataDataReader_ptr _duplicate (ParticipantBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static ParticipantBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      ParticipantBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (ParticipantBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (ParticipantBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (ParticipantBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const ParticipantBuiltinTopicData& instance) = 0;

   protected:
      ParticipantBuiltinTopicDataDataReader () {};
      ~ParticipantBuiltinTopicDataDataReader () {};
   private:
      ParticipantBuiltinTopicDataDataReader (const ParticipantBuiltinTopicDataDataReader &);
      ParticipantBuiltinTopicDataDataReader & operator = (const ParticipantBuiltinTopicDataDataReader &);
   };

   class ParticipantBuiltinTopicDataDataReaderView
   :
      virtual public DataReaderView
   { 
   public:
      typedef ParticipantBuiltinTopicDataDataReaderView_ptr _ptr_type;
      typedef ParticipantBuiltinTopicDataDataReaderView_var _var_type;

      static ParticipantBuiltinTopicDataDataReaderView_ptr _duplicate (ParticipantBuiltinTopicDataDataReaderView_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static ParticipantBuiltinTopicDataDataReaderView_ptr _narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static ParticipantBuiltinTopicDataDataReaderView_ptr _nil () { return 0; }
      static const char * _local_id;
      ParticipantBuiltinTopicDataDataReaderView_ptr _this () { return this; }

      virtual Long read (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (ParticipantBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (ParticipantBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (ParticipantBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (ParticipantBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const ParticipantBuiltinTopicData& instance) = 0;

   protected:
      ParticipantBuiltinTopicDataDataReaderView () {};
      ~ParticipantBuiltinTopicDataDataReaderView () {};
   private:
      ParticipantBuiltinTopicDataDataReaderView (const ParticipantBuiltinTopicDataDataReaderView &);
      ParticipantBuiltinTopicDataDataReaderView & operator = (const ParticipantBuiltinTopicDataDataReaderView &);
   };

   struct TopicBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < TopicBuiltinTopicData, struct TopicBuiltinTopicDataSeq_uniq_> TopicBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < TopicBuiltinTopicDataSeq> TopicBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < TopicBuiltinTopicDataSeq> TopicBuiltinTopicDataSeq_out;
   class TopicBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef TopicBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef TopicBuiltinTopicDataTypeSupportInterface_var _var_type;

      static TopicBuiltinTopicDataTypeSupportInterface_ptr _duplicate (TopicBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static TopicBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      TopicBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      TopicBuiltinTopicDataTypeSupportInterface () {};
      ~TopicBuiltinTopicDataTypeSupportInterface () {};
   private:
      TopicBuiltinTopicDataTypeSupportInterface (const TopicBuiltinTopicDataTypeSupportInterface &);
      TopicBuiltinTopicDataTypeSupportInterface & operator = (const TopicBuiltinTopicDataTypeSupportInterface &);
   };

   class TopicBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef TopicBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef TopicBuiltinTopicDataDataWriter_var _var_type;

      static TopicBuiltinTopicDataDataWriter_ptr _duplicate (TopicBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static TopicBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      TopicBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual LongLong register_instance (const TopicBuiltinTopicData& instance_data) = 0;
      virtual LongLong register_instance_w_timestamp (const TopicBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const TopicBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const TopicBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const TopicBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long write_w_timestamp (const TopicBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const TopicBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long dispose_w_timestamp (const TopicBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const TopicBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const TopicBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (TopicBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const TopicBuiltinTopicData& instance_data) = 0;

   protected:
      TopicBuiltinTopicDataDataWriter () {};
      ~TopicBuiltinTopicDataDataWriter () {};
   private:
      TopicBuiltinTopicDataDataWriter (const TopicBuiltinTopicDataDataWriter &);
      TopicBuiltinTopicDataDataWriter & operator = (const TopicBuiltinTopicDataDataWriter &);
   };

   class TopicBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef TopicBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef TopicBuiltinTopicDataDataReader_var _var_type;

      static TopicBuiltinTopicDataDataReader_ptr _duplicate (TopicBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static TopicBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      TopicBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (TopicBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (TopicBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (TopicBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const TopicBuiltinTopicData& instance) = 0;

   protected:
      TopicBuiltinTopicDataDataReader () {};
      ~TopicBuiltinTopicDataDataReader () {};
   private:
      TopicBuiltinTopicDataDataReader (const TopicBuiltinTopicDataDataReader &);
      TopicBuiltinTopicDataDataReader & operator = (const TopicBuiltinTopicDataDataReader &);
   };

   class TopicBuiltinTopicDataDataReaderView
   :
      virtual public DataReaderView
   { 
   public:
      typedef TopicBuiltinTopicDataDataReaderView_ptr _ptr_type;
      typedef TopicBuiltinTopicDataDataReaderView_var _var_type;

      static TopicBuiltinTopicDataDataReaderView_ptr _duplicate (TopicBuiltinTopicDataDataReaderView_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static TopicBuiltinTopicDataDataReaderView_ptr _narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static TopicBuiltinTopicDataDataReaderView_ptr _nil () { return 0; }
      static const char * _local_id;
      TopicBuiltinTopicDataDataReaderView_ptr _this () { return this; }

      virtual Long read (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (TopicBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (TopicBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (TopicBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (TopicBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const TopicBuiltinTopicData& instance) = 0;

   protected:
      TopicBuiltinTopicDataDataReaderView () {};
      ~TopicBuiltinTopicDataDataReaderView () {};
   private:
      TopicBuiltinTopicDataDataReaderView (const TopicBuiltinTopicDataDataReaderView &);
      TopicBuiltinTopicDataDataReaderView & operator = (const TopicBuiltinTopicDataDataReaderView &);
   };

   struct PublicationBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < PublicationBuiltinTopicData, struct PublicationBuiltinTopicDataSeq_uniq_> PublicationBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < PublicationBuiltinTopicDataSeq> PublicationBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < PublicationBuiltinTopicDataSeq> PublicationBuiltinTopicDataSeq_out;
   class PublicationBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef PublicationBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef PublicationBuiltinTopicDataTypeSupportInterface_var _var_type;

      static PublicationBuiltinTopicDataTypeSupportInterface_ptr _duplicate (PublicationBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static PublicationBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      PublicationBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      PublicationBuiltinTopicDataTypeSupportInterface () {};
      ~PublicationBuiltinTopicDataTypeSupportInterface () {};
   private:
      PublicationBuiltinTopicDataTypeSupportInterface (const PublicationBuiltinTopicDataTypeSupportInterface &);
      PublicationBuiltinTopicDataTypeSupportInterface & operator = (const PublicationBuiltinTopicDataTypeSupportInterface &);
   };

   class PublicationBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef PublicationBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef PublicationBuiltinTopicDataDataWriter_var _var_type;

      static PublicationBuiltinTopicDataDataWriter_ptr _duplicate (PublicationBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static PublicationBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      PublicationBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual LongLong register_instance (const PublicationBuiltinTopicData& instance_data) = 0;
      virtual LongLong register_instance_w_timestamp (const PublicationBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const PublicationBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const PublicationBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const PublicationBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long write_w_timestamp (const PublicationBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const PublicationBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long dispose_w_timestamp (const PublicationBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const PublicationBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const PublicationBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (PublicationBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const PublicationBuiltinTopicData& instance_data) = 0;

   protected:
      PublicationBuiltinTopicDataDataWriter () {};
      ~PublicationBuiltinTopicDataDataWriter () {};
   private:
      PublicationBuiltinTopicDataDataWriter (const PublicationBuiltinTopicDataDataWriter &);
      PublicationBuiltinTopicDataDataWriter & operator = (const PublicationBuiltinTopicDataDataWriter &);
   };

   class PublicationBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef PublicationBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef PublicationBuiltinTopicDataDataReader_var _var_type;

      static PublicationBuiltinTopicDataDataReader_ptr _duplicate (PublicationBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static PublicationBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      PublicationBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (PublicationBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (PublicationBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (PublicationBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const PublicationBuiltinTopicData& instance) = 0;

   protected:
      PublicationBuiltinTopicDataDataReader () {};
      ~PublicationBuiltinTopicDataDataReader () {};
   private:
      PublicationBuiltinTopicDataDataReader (const PublicationBuiltinTopicDataDataReader &);
      PublicationBuiltinTopicDataDataReader & operator = (const PublicationBuiltinTopicDataDataReader &);
   };

   class PublicationBuiltinTopicDataDataReaderView
   :
      virtual public DataReaderView
   { 
   public:
      typedef PublicationBuiltinTopicDataDataReaderView_ptr _ptr_type;
      typedef PublicationBuiltinTopicDataDataReaderView_var _var_type;

      static PublicationBuiltinTopicDataDataReaderView_ptr _duplicate (PublicationBuiltinTopicDataDataReaderView_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static PublicationBuiltinTopicDataDataReaderView_ptr _narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static PublicationBuiltinTopicDataDataReaderView_ptr _nil () { return 0; }
      static const char * _local_id;
      PublicationBuiltinTopicDataDataReaderView_ptr _this () { return this; }

      virtual Long read (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (PublicationBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (PublicationBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (PublicationBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (PublicationBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const PublicationBuiltinTopicData& instance) = 0;

   protected:
      PublicationBuiltinTopicDataDataReaderView () {};
      ~PublicationBuiltinTopicDataDataReaderView () {};
   private:
      PublicationBuiltinTopicDataDataReaderView (const PublicationBuiltinTopicDataDataReaderView &);
      PublicationBuiltinTopicDataDataReaderView & operator = (const PublicationBuiltinTopicDataDataReaderView &);
   };

   struct SubscriptionBuiltinTopicDataSeq_uniq_ {};
   typedef DDS_DCPSUVLSeq < SubscriptionBuiltinTopicData, struct SubscriptionBuiltinTopicDataSeq_uniq_> SubscriptionBuiltinTopicDataSeq;
   typedef DDS_DCPSSequence_var < SubscriptionBuiltinTopicDataSeq> SubscriptionBuiltinTopicDataSeq_var;
   typedef DDS_DCPSSequence_out < SubscriptionBuiltinTopicDataSeq> SubscriptionBuiltinTopicDataSeq_out;
   class SubscriptionBuiltinTopicDataTypeSupportInterface
   :
      virtual public TypeSupport
   { 
   public:
      typedef SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _ptr_type;
      typedef SubscriptionBuiltinTopicDataTypeSupportInterface_var _var_type;

      static SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _duplicate (SubscriptionBuiltinTopicDataTypeSupportInterface_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _nil () { return 0; }
      static const char * _local_id;
      SubscriptionBuiltinTopicDataTypeSupportInterface_ptr _this () { return this; }


   protected:
      SubscriptionBuiltinTopicDataTypeSupportInterface () {};
      ~SubscriptionBuiltinTopicDataTypeSupportInterface () {};
   private:
      SubscriptionBuiltinTopicDataTypeSupportInterface (const SubscriptionBuiltinTopicDataTypeSupportInterface &);
      SubscriptionBuiltinTopicDataTypeSupportInterface & operator = (const SubscriptionBuiltinTopicDataTypeSupportInterface &);
   };

   class SubscriptionBuiltinTopicDataDataWriter
   :
      virtual public DataWriter
   { 
   public:
      typedef SubscriptionBuiltinTopicDataDataWriter_ptr _ptr_type;
      typedef SubscriptionBuiltinTopicDataDataWriter_var _var_type;

      static SubscriptionBuiltinTopicDataDataWriter_ptr _duplicate (SubscriptionBuiltinTopicDataDataWriter_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static SubscriptionBuiltinTopicDataDataWriter_ptr _narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataWriter_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataWriter_ptr _nil () { return 0; }
      static const char * _local_id;
      SubscriptionBuiltinTopicDataDataWriter_ptr _this () { return this; }

      virtual LongLong register_instance (const SubscriptionBuiltinTopicData& instance_data) = 0;
      virtual LongLong register_instance_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, const Time_t& source_timestamp) = 0;
      virtual Long unregister_instance (const SubscriptionBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long unregister_instance_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long write (const SubscriptionBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long write_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long dispose (const SubscriptionBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long dispose_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long writedispose (const SubscriptionBuiltinTopicData& instance_data, LongLong handle) = 0;
      virtual Long writedispose_w_timestamp (const SubscriptionBuiltinTopicData& instance_data, LongLong handle, const Time_t& source_timestamp) = 0;
      virtual Long get_key_value (SubscriptionBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const SubscriptionBuiltinTopicData& instance_data) = 0;

   protected:
      SubscriptionBuiltinTopicDataDataWriter () {};
      ~SubscriptionBuiltinTopicDataDataWriter () {};
   private:
      SubscriptionBuiltinTopicDataDataWriter (const SubscriptionBuiltinTopicDataDataWriter &);
      SubscriptionBuiltinTopicDataDataWriter & operator = (const SubscriptionBuiltinTopicDataDataWriter &);
   };

   class SubscriptionBuiltinTopicDataDataReader
   :
      virtual public DataReader
   { 
   public:
      typedef SubscriptionBuiltinTopicDataDataReader_ptr _ptr_type;
      typedef SubscriptionBuiltinTopicDataDataReader_var _var_type;

      static SubscriptionBuiltinTopicDataDataReader_ptr _duplicate (SubscriptionBuiltinTopicDataDataReader_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static SubscriptionBuiltinTopicDataDataReader_ptr _narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataReader_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataReader_ptr _nil () { return 0; }
      static const char * _local_id;
      SubscriptionBuiltinTopicDataDataReader_ptr _this () { return this; }

      virtual Long read (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (SubscriptionBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (SubscriptionBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (SubscriptionBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const SubscriptionBuiltinTopicData& instance) = 0;

   protected:
      SubscriptionBuiltinTopicDataDataReader () {};
      ~SubscriptionBuiltinTopicDataDataReader () {};
   private:
      SubscriptionBuiltinTopicDataDataReader (const SubscriptionBuiltinTopicDataDataReader &);
      SubscriptionBuiltinTopicDataDataReader & operator = (const SubscriptionBuiltinTopicDataDataReader &);
   };

   class SubscriptionBuiltinTopicDataDataReaderView
   :
      virtual public DataReaderView
   { 
   public:
      typedef SubscriptionBuiltinTopicDataDataReaderView_ptr _ptr_type;
      typedef SubscriptionBuiltinTopicDataDataReaderView_var _var_type;

      static SubscriptionBuiltinTopicDataDataReaderView_ptr _duplicate (SubscriptionBuiltinTopicDataDataReaderView_ptr obj);
      DDS::Boolean _local_is_a (const char * id);

      static SubscriptionBuiltinTopicDataDataReaderView_ptr _narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataReaderView_ptr _unchecked_narrow (DDS::Object_ptr obj);
      static SubscriptionBuiltinTopicDataDataReaderView_ptr _nil () { return 0; }
      static const char * _local_id;
      SubscriptionBuiltinTopicDataDataReaderView_ptr _this () { return this; }

      virtual Long read (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long take_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, ReadCondition_ptr a_condition) = 0;
      virtual Long read_next_sample (SubscriptionBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long take_next_sample (SubscriptionBuiltinTopicData& received_data, SampleInfo& sample_info) = 0;
      virtual Long read_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long take_next_instance (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ULong sample_states, ULong view_states, ULong instance_states) = 0;
      virtual Long read_next_instance_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long take_next_instance_w_condition (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq, Long max_samples, LongLong a_handle, ReadCondition_ptr a_condition) = 0;
      virtual Long return_loan (SubscriptionBuiltinTopicDataSeq& received_data, SampleInfoSeq& info_seq) = 0;
      virtual Long get_key_value (SubscriptionBuiltinTopicData& key_holder, LongLong handle) = 0;
      virtual LongLong lookup_instance (const SubscriptionBuiltinTopicData& instance) = 0;

   protected:
      SubscriptionBuiltinTopicDataDataReaderView () {};
      ~SubscriptionBuiltinTopicDataDataReaderView () {};
   private:
      SubscriptionBuiltinTopicDataDataReaderView (const SubscriptionBuiltinTopicDataDataReaderView &);
      SubscriptionBuiltinTopicDataDataReaderView & operator = (const SubscriptionBuiltinTopicDataDataReaderView &);
   };

}




#endif 
